spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务发现组件进行结合,通过  serviceId 转发到具体的微服务
          enabled: true                       #是否开启基于服务发现得路由规则
          lower-case-service-id: true         # 是否将服务名称转小写
      routes: # 路由可以有多个
        - id: user-router # 我们自定义的路由 ID，保持唯一
          uri: lb://user-server     # gateway网关从服务注册中心获取实例信息然后负载后路由
          predicates:     # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/user/**